name: Daily Telegram Exercise Message

on:
  schedule:
    # Exécute à 08h00 UTC tous les jours (ajustez selon votre fuseau horaire)
    - cron: '0 08 * * *'
  workflow_dispatch: # Permet aussi l'exécution manuelle

jobs:
  send-message:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run script
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python sport.py
